spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/banco_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  retiro:
    limite-diario: ${LIMITE_DIARIO:1000}